PRODUCT_USE_DYNAMIC_PARTITIONS := true
PRODUCT_BUILD_VENDOR_BOOT_IMAGE := true

BOARD_MOVE_RECOVERY_RESOURCES_TO_VENDOR_BOOT := true
BOARD_INCLUDE_RECOVERY_RAMDISK_IN_VENDOR_BOOT := true

AB_OTA_UPDATER := true

TARGET_NO_RECOVERY := false
BOARD_USES_RECOVERY_AS_BOOT := false

BOARD_SUPER_PARTITION_GROUPS := qti_dynamic_partitions
BOARD_QTI_DYNAMIC_PARTITIONS_PARTITION_LIST := \
    system system_ext product vendor odm vendor_dlkm odm_dlkm

# Encryption
TW_INCLUDE_CRYPTO := true
TW_INCLUDE_FBE := true
